In [1]:
import pandas as pd

In [2]:
data = pd.read_csv(r'C:\Users\HARISH\Desktop\Project -MSD\dataset.csv')

In [3]:
data.describe()

         Unnamed: 0         price
count  7.349575e+06  7.349575e+06
mean   3.674787e+06  1.784788e+02
std    2.121640e+06  4.171807e+02
min    0.000000e+00 -1.000000e+00
25%    1.837394e+06 -1.000000e+00
50%    3.674787e+06 -1.000000e+00
75%    5.512180e+06  9.900000e+01
max    7.349574e+06  4.499000e+03

In [5]:
data.dropna(subset = ['Ontology'], inplace = True)

In [6]:
data.head(20)

,Unnamed: 0,Date,uuid,userevent,price,product_id,Ontology
0,0,2019-01-14,007e188b-63b2-4c0b-9c74-2eb5a4cb1d9b,addToCart,337,PR923AT55PMADFMX,women>outerwear>vests
1,1,2019-01-14,007e188b-63b2-4c0b-9c74-2eb5a4cb1d9b,addToCart,337,PR923AT55PMADFMX,women>outerwear>vests
2,2,2019-01-14,007e188b-63b2-4c0b-9c74-2eb5a4cb1d9b,addToCart,337,PR923AT09IUWDFMX,women>outerwear>vests
3,3,2019-01-14,007e188b-63b2-4c0b-9c74-2eb5a4cb1d9b,addToCart,117,MA194AT06LOBDFMX,boys>topwear>sweatshirts
4,4,2019-01-14,007e188b-63b2-4c0b-9c74-2eb5a4cb1d9b,addToCart,117,MA194AT06LOBDFMX,boys>topwear>sweatshirts
5,5,2019-01-14,007e188b-63b2-4c0b-9c74-2eb5a4cb1d9b,addToCart,144,DI088AT09LNYDFMX,kids>topwear>sweatshirts
6,6,2019-01-14,007e188b-63b2-4c0b-9c74-2eb5a4cb1d9b,addToCart,79,MA194AC62GDLDFMX,kids>accessories>others
7,7,2019-01-30,0094e7d4-df53-407d-9d0a-30d7371593da,addToCart,1699,TI778SH85SJUDFMX,women>shoes>boots
8,8,2019-01-29,009b1a92-9416-4acf-b194-dfde2042b062,addToCart,166,HP918AT06RIBDFMX,men>topwear>tshirts
9,9,2019-01-14,00b86337-8a95-4f9c-84af-b4a5ca99609e,addToCart,1599,GU531AC72PSDDFMX,women>bags>handbags
10,10,2019-01-14,00b86337-8a95-4f9c-84af-b4a5ca99609e,addToCart,1599,GU531AC72PSDDFMX,women>bags>handbags
11,11,2019-01-14,00b86337-8a95-4f9c-84af-b4a5ca99609e,addToCart,1599,GU531AC53IBUDFMX,women>bags>backpacks
12,12,2019-01-14,00b86337-8a95-4f9c-84af-b4a5ca99609e,addToCart,1599,GU531AC53IBUDFMX,women>bags>backpacks
13,13,2019-01-29,00b95eb3-3a21-4f98-9bae-481f6dc2fb42,addToCart,1499,TI778SH87SJSDFMX,men>shoes>boots
14,14,2019-01-29,00b95eb3-3a21-4f98-9bae-481f6dc2fb42,addToCart,1499,TI778SH87SJSDFMX,men>shoes>boots
15,15,2019-01-29,00b95eb3-3a21-4f98-9bae-481f6dc2fb42,addToCart,1499,TI778SH87SJSDFMX,men>shoes>boots
19,19,2019-01-30,00cd833b-981b-439e-aa02-d1421fdf5ac0,addToCart,1333,GU531AC53IBUDFMX,women>bags>backpacks
20,20,2019-01-30,00cd833b-981b-439e-aa02-d1421fdf5ac0,addToCart,1333,GU531AC53IBUDFMX,women>bags>backpacks
21,21,2019-01-30,00cd833b-981b-439e-aa02-d1421fdf5ac0,addToCart,1333,GU531AC53IBUDFMX,women>bags>backpacks
22,22,2019-01-30,00cd833b-981b-439e-aa02-d1421fdf5ac0,addToCart,1333,GU531AC53IBUDFMX,women>bags>backpacks

In [7]:
data

,Unnamed: 0,Date,uuid,userevent,price,product_id,Ontology
0,0,2019-01-14,007e188b-63b2-4c0b-9c74-2eb5a4cb1d9b,addToCart,337,PR923AT55PMADFMX,women>outerwear>vests
1,1,2019-01-14,007e188b-63b2-4c0b-9c74-2eb5a4cb1d9b,addToCart,337,PR923AT55PMADFMX,women>outerwear>vests
2,2,2019-01-14,007e188b-63b2-4c0b-9c74-2eb5a4cb1d9b,addToCart,337,PR923AT09IUWDFMX,women>outerwear>vests
3,3,2019-01-14,007e188b-63b2-4c0b-9c74-2eb5a4cb1d9b,addToCart,117,MA194AT06LOBDFMX,boys>topwear>sweatshirts
4,4,2019-01-14,007e188b-63b2-4c0b-9c74-2eb5a4cb1d9b,addToCart,117,MA194AT06LOBDFMX,boys>topwear>sweatshirts
...,...,...,...,...,...,...,...
7349560,7349560,2019-07-25,0babc325-1a0f-4894-abce-92a9786570c2,pageView,699,LE063AB71MRGDFMX,men>bottomwear>jeans
7349561,7349561,2019-07-25,0babc325-1a0f-4894-abce-92a9786570c2,pageView,899,LE063AB66RYZDFMX,men>bottomwear>pants
7349570,7349570,2019-07-29,97c5469a-0337-49c7-8b11-f2838df58aa3,pageView,1399,GU531AT88VKPDFMX,women>dresses>maxi
7349571,7349571,2019-07-29,97c5469a-0337-49c7-8b11-f2838df58aa3,pageView,1399,GU531AT88VKPDFMX,women>dresses>maxi
7349572,7349572,2019-07-29,97c5469a-0337-49c7-8b11-f2838df58aa3,pageView,1399,GU531AT88VKPDFMX,women>dresses>maxi

In [8]:
data[['people','category','mainproduct','product']] = data.Ontology.str.split(">",expand=True,)

In [9]:
data

,Unnamed: 0,Date,uuid,userevent,price,product_id,Ontology,people,category,mainproduct,product
0,0,2019-01-14,007e188b-63b2-4c0b-9c74-2eb5a4cb1d9b,addToCart,337,PR923AT55PMADFMX,women>outerwear>vests,women,outerwear,vests,None
1,1,2019-01-14,007e188b-63b2-4c0b-9c74-2eb5a4cb1d9b,addToCart,337,PR923AT55PMADFMX,women>outerwear>vests,women,outerwear,vests,None
2,2,2019-01-14,007e188b-63b2-4c0b-9c74-2eb5a4cb1d9b,addToCart,337,PR923AT09IUWDFMX,women>outerwear>vests,women,outerwear,vests,None
3,3,2019-01-14,007e188b-63b2-4c0b-9c74-2eb5a4cb1d9b,addToCart,117,MA194AT06LOBDFMX,boys>topwear>sweatshirts,boys,topwear,sweatshirts,None
4,4,2019-01-14,007e188b-63b2-4c0b-9c74-2eb5a4cb1d9b,addToCart,117,MA194AT06LOBDFMX,boys>topwear>sweatshirts,boys,topwear,sweatshirts,None
...,...,...,...,...,...,...,...,...,...,...,...
7349560,7349560,2019-07-25,0babc325-1a0f-4894-abce-92a9786570c2,pageView,699,LE063AB71MRGDFMX,men>bottomwear>jeans,men,bottomwear,jeans,None
7349561,7349561,2019-07-25,0babc325-1a0f-4894-abce-92a9786570c2,pageView,899,LE063AB66RYZDFMX,men>bottomwear>pants,men,bottomwear,pants,None
7349570,7349570,2019-07-29,97c5469a-0337-49c7-8b11-f2838df58aa3,pageView,1399,GU531AT88VKPDFMX,women>dresses>maxi,women,dresses,maxi,None
7349571,7349571,2019-07-29,97c5469a-0337-49c7-8b11-f2838df58aa3,pageView,1399,GU531AT88VKPDFMX,women>dresses>maxi,women,dresses,maxi,None
7349572,7349572,2019-07-29,97c5469a-0337-49c7-8b11-f2838df58aa3,pageView,1399,GU531AT88VKPDFMX,women>dresses>maxi,women,dresses,maxi,None

In [10]:
data.drop('Unnamed: 0',axis = 1,inplace = True)

In [11]:
#Removing the rows that has -1
data.drop(data.loc[data['price']==-1].index, inplace=True)

In [12]:
data

,Date,uuid,userevent,price,product_id,Ontology,people,category,mainproduct,product
0,2019-01-14,007e188b-63b2-4c0b-9c74-2eb5a4cb1d9b,addToCart,337,PR923AT55PMADFMX,women>outerwear>vests,women,outerwear,vests,None
1,2019-01-14,007e188b-63b2-4c0b-9c74-2eb5a4cb1d9b,addToCart,337,PR923AT55PMADFMX,women>outerwear>vests,women,outerwear,vests,None
2,2019-01-14,007e188b-63b2-4c0b-9c74-2eb5a4cb1d9b,addToCart,337,PR923AT09IUWDFMX,women>outerwear>vests,women,outerwear,vests,None
3,2019-01-14,007e188b-63b2-4c0b-9c74-2eb5a4cb1d9b,addToCart,117,MA194AT06LOBDFMX,boys>topwear>sweatshirts,boys,topwear,sweatshirts,None
4,2019-01-14,007e188b-63b2-4c0b-9c74-2eb5a4cb1d9b,addToCart,117,MA194AT06LOBDFMX,boys>topwear>sweatshirts,boys,topwear,sweatshirts,None
...,...,...,...,...,...,...,...,...,...,...
7349560,2019-07-25,0babc325-1a0f-4894-abce-92a9786570c2,pageView,699,LE063AB71MRGDFMX,men>bottomwear>jeans,men,bottomwear,jeans,None
7349561,2019-07-25,0babc325-1a0f-4894-abce-92a9786570c2,pageView,899,LE063AB66RYZDFMX,men>bottomwear>pants,men,bottomwear,pants,None
7349570,2019-07-29,97c5469a-0337-49c7-8b11-f2838df58aa3,pageView,1399,GU531AT88VKPDFMX,women>dresses>maxi,women,dresses,maxi,None
7349571,2019-07-29,97c5469a-0337-49c7-8b11-f2838df58aa3,pageView,1399,GU531AT88VKPDFMX,women>dresses>maxi,women,dresses,maxi,None
7349572,2019-07-29,97c5469a-0337-49c7-8b11-f2838df58aa3,pageView,1399,GU531AT88VKPDFMX,women>dresses>maxi,women,dresses,maxi,None

In [14]:
data.drop(['Ontology'],axis =1,inplace = True)

In [17]:
data

,Date,uuid,userevent,price,product_id,people,category,mainproduct,product
0,2019-01-14,007e188b-63b2-4c0b-9c74-2eb5a4cb1d9b,addToCart,337,PR923AT55PMADFMX,women,outerwear,vests,None
1,2019-01-14,007e188b-63b2-4c0b-9c74-2eb5a4cb1d9b,addToCart,337,PR923AT55PMADFMX,women,outerwear,vests,None
2,2019-01-14,007e188b-63b2-4c0b-9c74-2eb5a4cb1d9b,addToCart,337,PR923AT09IUWDFMX,women,outerwear,vests,None
3,2019-01-14,007e188b-63b2-4c0b-9c74-2eb5a4cb1d9b,addToCart,117,MA194AT06LOBDFMX,boys,topwear,sweatshirts,None
4,2019-01-14,007e188b-63b2-4c0b-9c74-2eb5a4cb1d9b,addToCart,117,MA194AT06LOBDFMX,boys,topwear,sweatshirts,None
...,...,...,...,...,...,...,...,...,...
7349560,2019-07-25,0babc325-1a0f-4894-abce-92a9786570c2,pageView,699,LE063AB71MRGDFMX,men,bottomwear,jeans,None
7349561,2019-07-25,0babc325-1a0f-4894-abce-92a9786570c2,pageView,899,LE063AB66RYZDFMX,men,bottomwear,pants,None
7349570,2019-07-29,97c5469a-0337-49c7-8b11-f2838df58aa3,pageView,1399,GU531AT88VKPDFMX,women,dresses,maxi,None
7349571,2019-07-29,97c5469a-0337-49c7-8b11-f2838df58aa3,pageView,1399,GU531AT88VKPDFMX,women,dresses,maxi,None
7349572,2019-07-29,97c5469a-0337-49c7-8b11-f2838df58aa3,pageView,1399,GU531AT88VKPDFMX,women,dresses,maxi,None